name: bestquotes
description: A lot of quotes by famous people.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^2.0.0
  fluttertoast: ^8.0.9
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  quiver: ^3.1.0
  scrollable_positioned_list: ^0.3.2
  share_plus: ^4.0.8
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/quotes.db
